package com.lucas.soap;
/** Library Solos SOAP.
 * @author Lucas Napoli
 * @author https://github.com/lucasnapolilapenda/SoapServer
 * @version 1.1
 * @since 1.0
 */

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by Lucas
 * Services Interface
 *
 */
@WebService
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Interface {
    /**
     *
     * @return
     *     returns java.lang.String
     *     List of books
     */
    @WebMethod
    String listAllBooks();


    /**
     *
     * @return
     *     returns java.lang.String
     *     Info by ID
     * @param id is the id a integer to find a book
     *
     */
    @WebMethod
    String getBookInfo (Integer id);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Info by isbn
     * @param isbn is the ISBN a String to find a book
     */

    @WebMethod
    String getBookInfoByISBN (String isbn);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Add Book
     * @param book is the book as an object with the properties
     */

    @WebMethod
    String addBook (Book book);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Update Book
     * @param book is the book as an object with the properties
     */

    @WebMethod
    String updateBookInfo (Book book);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Delete Book
     * @param id is the id a integer to find a book
     */

    @WebMethod
    String deleteBook (Integer id);

}
