package com.lucas.soap;
/** Library Solos SOAP.
 * @author Lucas Napoli
 * @author https://github.com/lucasnapolilapenda/SoapActivity/tree/master/src/main/java/com/lucas/soap
 * @version 1.1
 * @since 1.0
 */

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by Lucas
 * Services Interface
 *
 */
@WebService
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Interface {
    /**
     *
     * @return
     *     returns java.lang.String
     *     List of books
     */
    @WebMethod
    String listAllBooks();
    /**
     *
     * @return
     *     returns java.lang.String
     *     Info by ID
     * @param id
     *
     */

    @WebMethod
    String getBookInfo (Integer id);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Info by isbn
     * @param isbn
     */

    @WebMethod
    String getBookInfoByISBN (String isbn);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Add Book
     * @param book
     */

    @WebMethod
    String addBook (Book book);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Add Book
     * @param book
     */

    @WebMethod
    String updateBookInfo (Book book);
    /**
     *
     * @return
     *     returns java.lang.String
     *     Add Book
     * @param id
     */

    @WebMethod
    String deleteBook (Integer id);

}
